name = "naslook-api"
main = "src/app.ts"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat"]
minify = true

[env.dev]
vars = { ALLOWED_HOST = "*", ENV = "dev", LOG_LEVEL = "debug" }
d1_databases = [
    { binding = "DB", database_name = "naslook-db-prod", database_id = "10dcfedc-1354-43df-a47b-12f9a4691971", migrations_dir = "src/db/migrations" },
]

[env.stage]
name = "naslook-api-stage"
workers_dev = true
vars = { ALLOWED_HOST = "*", ENV = "stage", LOG_LEVEL = "debug" }
d1_databases = [
    { binding = "DB", database_name = "naslook-db-prod", database_id = "10dcfedc-1354-43df-a47b-12f9a4691971", migrations_dir = "src/db/migrations" },
]

[env.prod]
name = "naslook-api-prod"
workers_dev = true
vars = { ALLOWED_HOST = "*", ENV = "prod", LOG_LEVEL = "info" }
d1_databases = [
    { binding = "DB", database_name = "naslook-db-prod", database_id = "10dcfedc-1354-43df-a47b-12f9a4691971", migrations_dir = "src/db/migrations" },
]

[observability]
enabled = true
head_sampling_rate = 1

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"


# [ai]
# binding = "AI"
